name: Deploy to DO

on:
    push:
        branches:
            - master
        paths:
            - "server/**"
            - "engine/**"
            - ".github/workflows/server_cd.yml"

env:
    IMAGE_NAME: chess-server
    REGISTRY: registry.digitalocean.com/zaiamlata-container

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout repo
            uses: actions/checkout@v3

          - name: Install doctl 
            uses: digitalocean/action-doctl@v2
            with:
              token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

          - name: Log in to DO Container Registry 
            run: doctl registry login --expiry-seconds 600

          - name: Cache Docker build layers
            uses: docker/setup-buildx-action@v1

          - name: Build and push
            uses: docker/build-push-action@v2
            id: build-image
            with:
                context: .
                file: server/Dockerfile
                push: true
                tags: ${{ env.REGISTRY }}:latest
                cache-from: type=gha
                cache-to: type=gha,mode=max